# Generated by Django 3.1 on 2020-08-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
